---
- name: Deploy Kubernetes resources via master control node.
  hosts: master[0]
  gather_facts: true

  collections:
    - kubernetes.core

  environment:
    # The location of the kubeconfig file on the master.
    K8S_AUTH_KUBECONFIG: "{{ kubeconfig }}"

  pre_tasks:
    # Install required packages
    - name: Ensure pip, git and jq are installed.
      package:
        name:
          - python3-pip
          - python3-setuptools
          - git
          - jq
        state: present
      become: true
      tags: ["always"]

    - name: Ensure kubernetes Python library is installed.
      pip:
        name: kubernetes
        state: present
      become: true
      tags: ["always"]

    # Install Helm diff plugin to have a better idempotence check
    - name: Install diff Helm Plugin
      kubernetes.core.helm_plugin:
        plugin_path: "https://github.com/databus23/helm-diff"
        state: present
      tags: ["always"]
      register: helm_plugin
      until: helm_plugin is not failed
      retries: 5

  roles:
    - role: metallb
      tags: ["metallb"]
    - role: certmanager
      tags: ["certmanager"]
    - role: linkerd/control_plane
      tags: ["linkerd"]
      when: linkerd_enabled
    - role: traefik
      tags: ["traefik"]
    - role: longhorn
      tags: ["longhorn"]
