---
- name: Setup for k3s cluster install
  hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
    - role: prereq

- name: Install masters
  hosts: master
  become: yes
  roles:
    - role: k3s/master

- name: Install nodes
  hosts: node
  become: yes
  roles:
    - role: k3s/node

- name: Check k3s cluster status
  hosts: master[0]
  gather_facts: no
  become: yes

  tasks:
    - name: Check all nodes are ready
      shell:
        cmd: |
          JSONPATH='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}'
          kubectl get nodes -o jsonpath="$JSONPATH" | grep -o "Ready=True" | uniq | wc -l
      register: nodes_ready
      until: nodes_ready.stdout | int == 1
      retries: "{{ retry_count | default(10) }}"
      delay: 10
      changed_when: false
