---

- name: Deploy Kubernetes resources via master control node.
  hosts: master[0]
  gather_facts: true

  collections:
    - kubernetes.core

  environment:
    # The location of the kubeconfig file on the master.
    K8S_AUTH_KUBECONFIG: "{{ kubeconfig }}"

  pre_tasks:
    - name: Update package cache Debian and derivatives
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 86400
      become: true
      when: ansible_os_family == "Debian"
      tags: ['always']

    - name: Update package cache Redhat and derivatives
      ansible.builtin.dnf:
        update_cache: yes
      become: true
      changed_when: false
      when: ansible_os_family == "RedHat"
      tags: ['always']

    # Install kubernetes core collection dependencies (kubernetes python package) using PIP.
    - name: Ensure pip and git are installed.
      package:
        name:
          - python3-pip
          - python3-setuptools
          - git
        state: present
      become: true
      tags: ['always']

    - name: Ensure kubernetes Python library is installed.
      pip:
        name: kubernetes
        state: present
      become: true
      tags: ['always']

    # Install Helm diff plugin to have a better idempotence check
    - name: Intall Helm Plugin
      kubernetes.core.helm_plugin:
        plugin_path: "https://github.com/databus23/helm-diff"
        state: present
      tags: ['always']

  roles:
    - role: metallb
      tags: ['metallb']
    - role: certmanager
      tags: ['certmanager']
