---

- name: Setup for k3s cluster install
  hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
    - role: prereq
    - role: download
    - role: raspberrypi

- name: Install masters
  hosts: master
  become: yes
  roles:
    - role: k3s/master
    - role: ricsanfre.k8s_cli
      vars:
        k8s_arch: "{{ 'amd64' if ansible_architecture == 'x86_64' else 'arm64' }}"
      when: inventory_hostname == groups['master'][0]

- name: Install nodes
  hosts: node
  become: yes
  roles:
    - role: k3s/node
