---
- name: Create longhorn namespace.
  kubernetes.core.k8s:
    name: "{{ longhorn_namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: Add longhorn chart repo.
  kubernetes.core.helm_repository:
    name: longhorn
    repo_url: "https://charts.longhorn.io"

- name: Deploy LongHorn Helm chart.
  kubernetes.core.helm:
    name: longhorn
    chart_ref: longhorn/longhorn
    chart_version: "{{ longhorn_chart_version }}"
    update_repo_cache: true
    release_namespace: "{{ longhorn_namespace }}"
    state: present
    wait: yes
    values:
      defaultSettings:
        defaultDataPath: "/storage"
        taintToleration: "node-role.kubernetes.io/master=true:NoSchedule"
  register: longhorn_install
  until: longhorn_install is not failed
  retries: 1

- name: Wait for longhorn pods to be ready, even if waiting the helm module
  command:
    cmd: "kubectl --kubeconfig {{ kubeconfig }} wait \
      --for=condition=Ready pod \
      --namespace={{ longhorn_namespace }} \
      --all \
      --timeout=120s"
  register: longhorn_pods_ready
  until: longhorn_pods_ready.rc == 0
  retries: 5
  changed_when: false

- name: Enable linkerd integration
  include_tasks: configure_linkerd_mesh.yml
  when: linkerd_enabled

- name: Create Ingress rule for Longhorn UI
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'templates/' + item) }}"
    state: present
  with_items:
    - longhorn_ingress.yml.j2

- name: Patching 'local-path' storage class. Set it as non-default
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: StorageClass
      metadata:
        name: local-path
        annotations:
          storageclass.kubernetes.io/is-default-class: "false"
    state: patched
