---
- name: Create longhorn namespace.
  kubernetes.core.k8s:
    name: "{{ longhorn_namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: Add longhorn chart repo.
  kubernetes.core.helm_repository:
    name: longhorn
    repo_url: "https://charts.longhorn.io"

- name: Copy longhorn health check script
  template:
    src: check_lh.sh.j2
    dest: /usr/local/bin/check_lh.sh
    owner: "root"
    group: "root"
    mode: "u=rwx,g=rx,o=rx"
  become: true

- name: Deploy LongHorn Helm chart.
  kubernetes.core.helm:
    name: longhorn
    chart_ref: longhorn/longhorn
    chart_version: "{{ longhorn_chart_version }}"
    update_repo_cache: true
    release_namespace: "{{ longhorn_namespace }}"
    state: present
    values:
      defaultSettings:
        defaultDataPath: "/storage"
        taintToleration: "node-role.kubernetes.io/master=true:NoSchedule"

- name: Check longhorn status. Wait for all components to start
  command:
    cmd: "/usr/local/bin/check_lh.sh"
  changed_when: false
  register: lh_status
  until: lh_status is not failed
  retries: 1

- name: Enable linkerd integration
  include_tasks: configure_linkerd_mesh.yml
  when: linkerd_enabled

- name: Create Ingress rule for Longhorn UI
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'templates/' + item) }}"
    state: present
  with_items:
    - longhorn_ingress.yml.j2

- name: Patching 'local-path' storage class. Set it as non-default
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: StorageClass
      metadata:
        name: local-path
        annotations:
          storageclass.kubernetes.io/is-default-class: "false"
    state: patched
