---
- name: Create longhorn namespace.
  kubernetes.core.k8s:
    name: "{{ longhorn_namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: Add rancher chart repo.
  kubernetes.core.helm_repository:
    name: longhorn
    repo_url: "https://charts.longhorn.io"

- name: Copy longhorn health check script
  copy:
    src: "files/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    owner: "root"
    group: "root"
    mode: "u=rwx,g=rx,o=rx"
  become: true
  with_items:
    - check_lh.sh

- name: Deploy LongHorn Helm chart.
  kubernetes.core.helm:
    name: longhorn
    chart_ref: longhorn/longhorn
    update_repo_cache: true
    release_namespace: "{{ longhorn_namespace }}"
    state: present
    values:
      defaultSettings:
        defaultDataPath: "/storage"
        taintToleration: "node-role.kubernetes.io/master=true:NoSchedule"

- name: Check longhorn status. Wait for all components to start
  command:
    cmd: "/usr/local/bin/check_lh.sh"
  changed_when: false

- name: Enable linkerd integration
  include_tasks: configure_linkerd_mesh.yml
  when: linkerd_enabled

- name: Create Ingress rule for Longhorn UI
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'templates/' + item) }}"
    state: present
  with_items:
    - longhorn_ingress.yml.j2

- name: Patching Local-path storage resource. Set it as non-default
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: StorageClass
      metadata:
        name: local-path
        annotations:
          storageclass.kubernetes.io/is-default-class: "false"
    state: patched
