---
- name: Remove Ingress rule for Longhorn UI
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'templates/' + item) }}"
    state: absent
  with_items:
    - longhorn_ingress.yml.j2

- name: Remove LongHorn Helm chart
  kubernetes.core.helm:
    name: longhorn
    chart_ref: longhorn/longhorn
    chart_version: "{{ longhorn_chart_version }}"
    release_namespace: "{{ longhorn_namespace }}"
    state: absent

- name: Remove longhorn chart repo.
  kubernetes.core.helm_repository:
    name: longhorn
    repo_url: "https://charts.longhorn.io"
    state: absent

- name: Remove longhorn namespace.
  kubernetes.core.k8s:
    name: "{{ longhorn_namespace }}"
    api_version: v1
    kind: Namespace
    state: absent

- name: Make sure 'local-path' storage class is default when Longhorn is disabled
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: StorageClass
      metadata:
        name: local-path
        annotations:
          storageclass.kubernetes.io/is-default-class: "true"
    state: patched
