# frozen_string_literal: true

no_of_masters = 3

Vagrant.configure('2') do |config|
  config.vbguest.auto_update = false
  config.vm.graceful_halt_timeout = 70
  (1..no_of_masters).each do |i|
    config.vm.define "master-#{i}" do |master|
      master.vm.box = 'generic/ubuntu2004'
      master.vm.hostname = "k3s-m#{i}"
      master.vm.network 'private_network', ip: "192.168.56.1#{i}"
      master.vm.provision 'shell' do |s|
        ssh_pub_key = File.readlines("#{ENV['HOME']}/.ssh/id_rsa.pub").first.strip
        s.inline = <<-SHELL
          echo "adding my own ssh public key..."
          echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
          echo "upgrading system..."
          apt update -y
          apt -y upgrade
          echo "adding nodes to /etc/hosts file..."
          for n in {1..#{no_of_masters}}
          do
            echo "192.168.56.1$n k3s-m$n" >> /etc/hosts
          done
          # longhorn
          echo "Setting Longhorn prereqs..."
          # https://longhorn.io/kb/troubleshooting-volume-with-multipath/
          echo -e 'blacklist {\n devnode "^sd[a-z0-9]+"\n}' >> /etc/multipath.conf
          systemctl restart multipathd
          apt install -y open-iscsi net-tools
          apt -y autoremove
          # tweak sysctl.conf
          echo 'fs.inotify.max_user_instances=1280' >> /etc/sysctl.conf
          echo 'fs.inotify.max_user_watches=655360' >> /etc/sysctl.conf
          echo 'vm.swappiness=10' >> /etc/sysctl.conf
          sysctl -p
        SHELL
      end
      master.vm.provider 'virtualbox' do |v|
        v.memory = 6144
        v.cpus = 2
      end
    end
  end
end
