---
- name: Create Metal LB namespace.
  kubernetes.core.k8s:
    name: "{{ metallb_namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: Add Metal LB chart repo.
  kubernetes.core.helm_repository:
    name: metallb
    repo_url: "https://metallb.github.io/metallb"

- name: Deploy Metal LB Helm chart.
  kubernetes.core.helm:
    name: metallb
    chart_ref: metallb/metallb
    chart_version: "{{ metallb_chart_version }}"
    release_namespace: "{{ metallb_namespace }}"
    update_repo_cache: true
    state: present

- name: Wait for pods to be ready
  command:
    cmd: "kubectl --kubeconfig {{ kubeconfig }} wait \
      --for=condition=Ready pod \
      --namespace={{ metallb_namespace }} \
      --all \
      --timeout=120s"
  register: metallb_pods_ready
  until: metallb_pods_ready.rc == 0
  retries: 5
  changed_when: false

- name: Configure IP address pool
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'templates/' + item) }}"
    state: present
  with_items:
    - metallb_config.yml.j2
  # random fails
  register: ip_addr_pool_set
  until: ip_addr_pool_set is not failed
  retries: 5
