---
# External Roles
####################################
# ricsanfre.k8s_cli role variables #
####################################
install_helm: true
install_kubectl: false
k8s_platform: linux
helm_version: 'v3.10.0'
#################

k3s_version: v1.24.4+k3s1
# this is the user that has ssh access to these machines
ansible_user: ansibleuser
systemd_dir: /etc/systemd/system
kubeconfig: ~/.kube/config

# Set your timezone
system_timezone: "Your/Timezone"

# interface which will be used for flannel
flannel_iface: "eth0"

# apiserver_endpoint is virtual ip-address which will be configured on each master
apiserver_endpoint: "192.168.30.222"

# k3s_token is required  masters can talk together securely
# this token should be alphanumeric only
k3s_token: "some-SUPER-DEDEUPER-secret-password"

# The IP on which the node is reachable in the cluster.
# Here, a sensible default is provided, you can still override
# it for each of your hosts, though.
k3s_node_ip: '{{ ansible_facts[flannel_iface]["ipv4"]["address"] }}'

k3s_node_exists: "{{ 'true' if groups['node'] | default([]) | length >= 1 else 'false' }}"

# these arguments are recommended for servers as well as agents:
extra_args: >-
  --flannel-iface={{ flannel_iface }}
  --node-ip={{ k3s_node_ip }}

# change these to your liking, the only required are: --disable servicelb, --tls-san {{ apiserver_endpoint }}
extra_server_args: >-
  {{ extra_args }}
  --tls-san {{ apiserver_endpoint }}
  {{ '--node-taint node-role.kubernetes.io/master=true:NoSchedule' if k3s_node_exists | bool else '' }}
  --disable servicelb
  --disable traefik
  --kubelet-arg 'config=/etc/rancher/k3s/kubelet.config'
  --kube-controller-manager-arg 'bind-address=0.0.0.0'
  --kube-proxy-arg 'metrics-bind-address=0.0.0.0'
  --kube-scheduler-arg 'bind-address=0.0.0.0'
  --etcd-expose-metrics 'true'
extra_agent_args: >-
  {{ extra_args }}

# k3s config directory
k3s_config_directory: /etc/rancher/k3s

# kubelet configuration
k3s_kubelet_config: |
  apiVersion: kubelet.config.k8s.io/v1beta1
  kind: KubeletConfiguration
  shutdownGracePeriod: 60s
  shutdownGracePeriodCriticalPods: 20s

# image tag for kube-vip
kube_vip_tag_version: "v0.5.0"

# metallb related
# helm chart version
metallb_chart_version: "0.13.5"
# ip range for load balancer
metallb_ip_range: "192.168.30.80-192.168.30.90"

# certmanager
certmanager_chart_version: 1.9.1
