---
####################################
# ricsanfre.k8s_cli role variables #
####################################
install_helm: true
install_kubectl: false
k8s_platform: linux
# put 'arm64' for pi
k8s_arch: amd64
