---
- name: Apply overrides
  ansible.builtin.import_playbook: >-
    {{ lookup("ansible.builtin.env", "MOLECULE_SCENARIO_DIRECTORY") }}/overrides.yml

- name: Verify
  # use our 1st master for testing the k3s cluster
  hosts: control1

  pre_tasks:
    - name: Create temporary directory for kubecfg
      ansible.builtin.tempfile:
        state: directory
        suffix: kubecfg
      register: kubecfg
    - name: Download kubecfg
      ansible.builtin.fetch:
        src: "{{ ansible_env.HOME }}/.kube/config"
        dest: "{{ kubecfg.path }}/"
        flat: true
    - name: Store path to kubecfg
      ansible.builtin.set_fact:
        kubecfg_path: "{{ kubecfg.path }}/config"

  roles:
    - verify/from_outside

  post_tasks:
    - name: Clean up kubecfg
      ansible.builtin.file:
        path: "{{ kubecfg.path }}"
        state: absent
