---
# Get list of packages installed
- name: Get list of packages
  package_facts:
    manager: auto

- name: Check whether snap package is installed
  debug:
    msg: "snapd found"
  when: "'snapd' in ansible_facts.packages"

- name: Remove snap package
  include_tasks: remove_snap.yml
  when: "'snapd' in ansible_facts.packages"

- name: Set same timezone on every Server
  timezone:
    name: "{{ system_timezone }}"
  when: (system_timezone is defined) and (system_timezone != "Your/Timezone")

- name: Enable IPv4 forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: yes

- name: Enable IPv6 forwarding
  sysctl:
    name: net.ipv6.conf.all.forwarding
    value: "1"
    state: present
    reload: yes

- name: Enable IPv6 router advertisements
  sysctl:
    name: net.ipv6.conf.all.accept_ra
    value: "2"
    state: present
    reload: yes

- name: Add br_netfilter to /etc/modules-load.d/
  copy:
    content: "br_netfilter"
    dest: /etc/modules-load.d/br_netfilter.conf
    mode: "u=rw,g=,o="
  when: ansible_os_family == "RedHat"

- name: Load br_netfilter
  modprobe:
    name: br_netfilter
    state: present
  when: ansible_os_family == "RedHat"

- name: Set bridge-nf-call-iptables (just to be sure)
  sysctl:
    name: "{{ item }}"
    value: "1"
    state: present
    reload: yes
  when: ansible_os_family == "RedHat"
  loop:
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables

- name: Add /usr/local/bin to sudo secure_path
  lineinfile:
    line: 'Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin'
    regexp: "Defaults(\\s)*secure_path(\\s)*="
    state: present
    insertafter: EOF
    path: /etc/sudoers
    validate: 'visudo -cf %s'
  when: ansible_os_family == "RedHat"

# https://rancher.com/docs/k3s/latest/en/advanced/#additional-preparation-for-red-hat-centos-enterprise-linux
- name: Stop and disable firewalld as suggested by the k3s docs
  ansible.builtin.service:
    name: firewalld
    state: stopped
    enabled: false
  when: ansible_os_family == "RedHat"

- name: Set SELinux state
  selinux:
    state: "{{ selinux_state }}"
    policy: targeted
  register: selinux_set
  vars:
    selinux_state: "{{ 'enforcing' if selinux_enabled else 'disabled' }}"
  when: ansible_os_family == "RedHat"

- name: Relabel filesystem if selinux becomes enabled
  ansible.builtin.file:
    path: /.autorelabel
    state: touch
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == "RedHat" and selinux_enabled and selinux_set.changed

- name: Reboot RedHat machines if selinux status changed
  reboot:
    reboot_timeout: 3600
  when: ansible_os_family == "RedHat" and selinux_set.changed

- name: K3s selinux policy repository gpg public key
  ansible.builtin.rpm_key:
    state: present
    key: https://rpm.rancher.io/public.key
  register: k3s_selinux_key
  until: k3s_selinux_key is not failed
  retries: 5
  when: ansible_os_family == "RedHat" and selinux_enabled

- name: Install required k3s selinux dependencies
  ansible.builtin.dnf:
    name:
      - container-selinux
      - selinux-policy-base
      - "{{ k3s_selinux }}"
    state: present
    update_cache: true
  register: k3s_selinux_prereqs_installed
  until: k3s_selinux_prereqs_installed is not failed
  retries: 5
  when: ansible_os_family == "RedHat" and selinux_enabled

- name: Install required longhorn dependencies in RedHat derivatives
  ansible.builtin.dnf:
    name:
      - iscsi-initiator-utils
      - nfs-utils
    state: present
    update_cache: true
  register: longhorn_redhat
  when: ansible_os_family == 'RedHat' and longhorn_enabled

- name: Install required longhorn dependencies in Debian derivatives
  ansible.builtin.apt:
    name:
      - open-iscsi
      - nfs-common
    state: present
    update_cache: true
  register: longhorn_debian
  when: ansible_os_family == 'Debian' and longhorn_enabled

- name: Setup iscsi initiator name in RedHat derivatives
  shell:
    cmd: echo "InitiatorName=$(/sbin/iscsi-iname)" > /etc/iscsi/initiatorname.iscsi
  when: ansible_os_family == 'RedHat' and longhorn_redhat.changed

- name: Enable iscsid service for Longhorn
  ansible.builtin.systemd:
    name: iscsid
    state: restarted
    daemon_reload: yes
    enabled: yes
  when: longhorn_redhat.changed or longhorn_debian.changed

- name: Load the required Longhorn kernel modules
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - iscsi_tcp
    - nfs
  when: longhorn_redhat.changed or longhorn_debian.changed
