---
- name: Create cert-manager namespace.
  kubernetes.core.k8s:
    name: "{{ certmanager_namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: Add Jetstack chart repo.
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: "https://charts.jetstack.io"

- name: Deploy Cert-Manager Helm chart.
  kubernetes.core.helm:
    name: certmanager
    chart_ref: jetstack/cert-manager
    chart_version: "{{ certmanager_chart_version }}"
    update_repo_cache: true
    release_namespace: "{{ certmanager_namespace }}"
    state: present
    release_values:
      installCRDs: true

- name: Wait for pods to be ready
  command:
    cmd: "kubectl --kubeconfig {{ kubeconfig }} \
      wait --for=condition=Ready pod \
      --namespace={{ certmanager_namespace }} \
      --all \
      --timeout=120s"
  register: certmanager_pods_ready
  until: certmanager_pods_ready.rc == 0
  retries: 4
  delay: 10
  changed_when: false

- name: Configure Cluster Issuers
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'templates/' + item) }}"
    state: present
    wait: true
  with_items:
    - selfsigned_issuer.yml.j2
    - ca_issuer.yml.j2
  # random fails
  register: cluster_issuer_set
  until: cluster_issuer_set is not failed
  retries: 4
  delay: 10
