---
dependency:
  name: galaxy
driver:
  name: vagrant
.platform_presets:
  - &control
    memory: 2048
    cpus: 2
    groups:
      - k3s_cluster
      - master
  - &node
    memory: 2048
    cpus: 2
    groups:
      - k3s_cluster
      - node
  - &ubuntu
    box: generic/ubuntu2204
  - &debian
    box: generic/debian11
  - &centos
    box: generic/centos9s
  - &rocky
    box: generic/rocky9
  - &alma
    box: generic/alma9
platforms:
  - <<: [*control, *centos]
    name: control1
    interfaces:
      - network_name: private_network
        ip: 192.168.30.38
  - <<: [*control, *ubuntu]
    name: control2
    interfaces:
      - network_name: private_network
        ip: 192.168.30.39
  - <<: [*control, *rocky]
    name: control3
    interfaces:
      - network_name: private_network
        ip: 192.168.30.40
  - <<: [*node, *debian]
    name: node1
    interfaces:
      - network_name: private_network
        ip: 192.168.30.41
  - <<: [*node, *alma]
    name: node2
    interfaces:
      - network_name: private_network
        ip: 192.168.30.42
provisioner:
  name: ansible
  playbooks:
    converge: ../resources/converge.yml
    side_effect: ../resources/reset.yml
    verify: ../resources/verify.yml
  inventory:
    links:
      group_vars: ../../inventory/sample/group_vars
scenario:
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    # idempotence is not possible with the playbook in its current form.
    - verify
    # We are repurposing side_effect here to test the reset playbook.
    # This is why we do not run it before verify (which tests the cluster),
    # but after the verify step.
    - side_effect
    - cleanup
    - destroy
