---
- name: Apply overrides
  hosts: all
  tasks:
    - name: Override host variables
      ansible.builtin.set_fact:
        # The test VMs might be a bit slow, so we give them more time to join the cluster:
        retry_count: 45

        # override it to make kubeconfig easier to access in tests,
        # and we must again add the '--tls-san' because the already existing value is from our sample
        extra_server_args: >-
          --write-kubeconfig-mode 644
          {{ extra_server_args }}
