---
- name: Uninstall k3s cluster - masters
  shell:
    cmd: "k3s-uninstall.sh && echo 'done' || exit 0"
  register: k3s_master
  changed_when: k3s_master.stdout == 'done'
  when: inventory_hostname in groups['master']

- name: Uninstall k3s cluster - workers
  shell:
    cmd: "k3s-agent-uninstall.sh && echo 'done' || exit 0"
  register: k3s_worker
  changed_when: k3s_worker.stdout == 'done'
  when: groups['node'] is defined and inventory_hostname in groups['node']

- name: Remove kubernetes Python library
  pip:
    name: kubernetes
    state: absent
  when: inventory_hostname == groups['master'][0]

- name: Remove unneeded files and dirs
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /usr/local/bin/crictl
    - /usr/local/bin/kubectl
    - /usr/local/bin/helm
    - /usr/local/bin/linkerd
    - /etc/rancher
    - /var/lib/rancher
    - /root/.kube
    - ~{{ ansible_user }}/.kube
    - ~{{ ansible_user }}/.ansible
    - ~{{ ansible_user }}/.cache/helm
    - ~{{ ansible_user }}/.config/helm
    - ~{{ ansible_user }}/.local/share/helm
    - ~{{ ansible_user }}/.rancher

# Related to Longhorn and selinux
- name: Remove dependencies in RedHat derivatives
  ansible.builtin.dnf:
    name:
      - iscsi-initiator-utils
      - nfs-utils
      - k3s-selinux
    autoremove: true
    state: absent
  when: ansible_os_family == 'RedHat'

- name: Remove longhorn dependencies in Debian derivatives
  ansible.builtin.apt:
    name:
      - nfs-common
    autoremove: true
    state: absent
  when: ansible_os_family == 'Debian'
