---
- name: "Remove namespace: {{ testing_namespace }}"
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: "{{ testing_namespace }}"
    state: absent
    kubeconfig: "{{ kubecfg_path }}"

- name: Clean up kubecfg
  ansible.builtin.file:
    path: "{{ kubecfg.path }}"
    state: absent
