---

- name: Ensure htpasswd utility is installed
  package:
    name: "{{ 'httpd-tools' if ansible_os_family == 'RedHat' else 'apache2-utils' }}"
    state: 'present'
  become: true

- name: Use htpasswd utility to create the dashboard credentials
  shell:
    cmd: >-
      htpasswd -nb {{ traefik_basic_auth_user }} {{ traefik_basic_auth_passwd }} | base64
  register: htpasswd
  changed_when: false

- name: Set htpasswd pair
  set_fact:
    traefik_auth_htpasswd_pair: "{{ htpasswd.stdout }}"
