---
- name: Common Overrides
  ansible.builtin.set_fact:
    traefik_external_ip: 192.168.30.101
    traefik_dashboard_dns: traefik-three-masters.k3s-cluster.net
    longhorn_enabled: "{{ lookup('ansible.builtin.env', 'LONGHORN_ENABLED', default=True) }}"
    longhorn_dashboard_dns: longhorn-three-masters.k3s-cluster.net
